os: linux
dist: xenial
language: java

jdk:
  - openjdk8

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'

addons:
  sonarcloud:
    organization: "eliasmeyer-github"

before_install:
  - chmod +x mvnw

jobs:
  include:
    - stage: tests
      # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
      script: mvnw clean -Dorg.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=eliasmeyer_compasso-votemanager-api -Dsonar.login=${SONAR_TOKEN}
    - stage: deploy
      install: mvnw clean install -DskipTests
      script: skip
      provider: heroku
        api_key: ${HEROKU_TOKEN}
        app: eliasmeyer-compasso
        on: master
        skip_cleanup: true
